1、执行语句
UPDATE tphct02 SET BPO_QTY=1, BPO_PRICE=100, BPO_AMT=100*1, BPO_NOTAX_PRICE=100/(1+TAX_RATE), BPO_NOTAX_AMT=(100*1)/(1+TAX_RATE), OPS_REMARK='68598 合同信息修改' WHERE BPO_LINE_ID IN ('BPO-EXAMPLE-000001', 'BPO-EXAMPLE-000002', 'BPO-EXAMPLE-000003') AND ALIVE_FLAG='1';
-- 批量更新合同的主表汇总金额
UPDATE tphct01 SET BPO_AMT=(SELECT SUM(BPO_AMT) FROM tphct02 WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1'), TARGET_AMT=(SELECT SUM(BPO_AMT) FROM tphct02 WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1'), BPO_NOTAX_AMT=(SELECT SUM(BPO_NOTAX_AMT) FROM tphct02 WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1'), OPS_REMARK='68598 合同信息修改' WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1';
2、回退语句
UPDATE tphct02 SET BPO_QTY=50, BPO_PRICE=1, BPO_AMT=1*50, BPO_NOTAX_PRICE=1/(1+TAX_RATE), BPO_NOTAX_AMT=(1*50)/(1+TAX_RATE), OPS_REMARK='' WHERE BPO_LINE_ID IN ('BPO-EXAMPLE-000001', 'BPO-EXAMPLE-000002', 'BPO-EXAMPLE-000003') AND ALIVE_FLAG='1';
-- 回退合同主表
UPDATE tphct01 SET BPO_AMT=(SELECT SUM(BPO_AMT) FROM tphct02 WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1'), TARGET_AMT=(SELECT SUM(BPO_AMT) FROM tphct02 WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1'), BPO_NOTAX_AMT=(SELECT SUM(BPO_NOTAX_AMT) FROM tphct02 WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1'), OPS_REMARK='' WHERE BPO_ID='BPO-EXAMPLE' AND ALIVE_FLAG='1';
3.数据库
ip：192.168.11.71
库名：cnnc_ph