# Generated by Django 5.2.8 on 2025-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OrgDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plate_code", models.CharField(blank=True, max_length=255, null=True)),
                ("plate_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "org_detail",
            },
        ),
    ]
