# Generated by Django 5.2.8 on 2025-11-30 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemDetail",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("item_name", models.CharField(max_length=1000)),
                ("category", models.CharField(max_length=100)),
                ("item_uom", models.CharField(max_length=25)),
                ("purc_type", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "item_detail",
            },
        ),
    ]
