# Generated by Django 5.2.8 on 2025-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0002_itemdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_type", models.CharField(max_length=16)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("total", models.IntegerField(default=0)),
                ("done", models.IntegerField(default=0)),
                ("message", models.TextField(blank=True)),
                ("error", models.TextField(blank=True)),
                ("filename", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "import_job",
            },
        ),
    ]
