# Generated by Django 5.2.8 on 2025-12-06 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0003_importjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="DropdownGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "group_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分组编码"
                    ),
                ),
                (
                    "group_name",
                    models.CharField(max_length=100, verbose_name="分组名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="分组描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "下拉框配置分组",
                "verbose_name_plural": "下拉框配置分组",
                "db_table": "dropdown_group",
                "ordering": ["group_code"],
            },
        ),
        migrations.CreateModel(
            name="DropdownOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "option_code",
                    models.CharField(max_length=50, verbose_name="选项编码"),
                ),
                (
                    "option_label",
                    models.CharField(max_length=200, verbose_name="选项标签"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "is_system",
                    models.BooleanField(default=False, verbose_name="是否系统内置"),
                ),
                ("remark", models.TextField(blank=True, verbose_name="备注说明")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="work_tools.dropdowngroup",
                        verbose_name="所属分组",
                    ),
                ),
            ],
            options={
                "verbose_name": "下拉框配置项",
                "verbose_name_plural": "下拉框配置项",
                "db_table": "dropdown_option",
                "ordering": ["group", "sort_order", "option_code"],
                "indexes": [
                    models.Index(
                        fields=["group", "is_active"],
                        name="dropdown_op_group_i_216140_idx",
                    ),
                    models.Index(
                        fields=["option_code"], name="dropdown_op_option__c2dbcb_idx"
                    ),
                ],
                "unique_together": {("group", "option_code")},
            },
        ),
    ]
