# Generated by Django 5.2.8 on 2025-12-06 09:00

from django.db import migrations


def init_dropdown_data(apps, schema_editor):
    """初始化下拉框配置数据"""
    DropdownGroup = apps.get_model('work_tools', 'DropdownGroup')
    DropdownOption = apps.get_model('work_tools', 'DropdownOption')
    
    # 创建配置分组
    groups_data = [
        {
            'group_code': 'contract_status',
            'group_name': '合同状态',
            'description': '合同审批流程各阶段的状态值',
            'is_active': True,
        },
        {
            'group_code': 'importance_level',
            'group_name': '物项重要性',
            'description': '物项的重要性级别分类',
            'is_active': True,
        },
    ]
    
    groups = {}
    for group_data in groups_data:
        group = DropdownGroup.objects.create(**group_data)
        groups[group.group_code] = group
    
    # 创建配置项
    options_data = [
        # 合同状态
        {'group_code': 'contract_status', 'option_code': '', 'option_label': '-- 请选择合同状态 --', 'sort_order': 0, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'DELETE', 'option_label': '删除', 'sort_order': 1, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'DRAFT', 'option_label': '草稿', 'sort_order': 2, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'SUPPAPPROVED', 'option_label': '供应商已确认', 'sort_order': 3, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'SUPPREFUSE', 'option_label': '供应商拒绝', 'sort_order': 4, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'WAITINGFORSUPP', 'option_label': '待供应商确认', 'sort_order': 5, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'INPROCESSING', 'option_label': '审批中', 'sort_order': 6, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'APPROVED', 'option_label': '审批通过', 'sort_order': 7, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'REJECT', 'option_label': '驳回', 'sort_order': 8, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'ECONSENDING', 'option_label': '发送电子合同', 'sort_order': 9, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'ECONSENDED', 'option_label': '电子合同发送成功', 'sort_order': 10, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'ECONSIGNED', 'option_label': '已签约', 'sort_order': 11, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'ACTIVE', 'option_label': '生效', 'sort_order': 12, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'REVISION', 'option_label': '低版本修订', 'sort_order': 13, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'CLOSEDFORCE', 'option_label': '作废', 'sort_order': 14, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'LOCK', 'option_label': '冻结', 'sort_order': 15, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'STOP', 'option_label': '合同终止', 'sort_order': 16, 'is_system': True},
        {'group_code': 'contract_status', 'option_code': 'CLOSED', 'option_label': '已失效', 'sort_order': 17, 'is_system': True},
        
        # 物项重要性
        {'group_code': 'importance_level', 'option_code': '0', 'option_label': '一般准入备案类 0', 'sort_order': 1, 'is_system': True},
        {'group_code': 'importance_level', 'option_code': '1', 'option_label': '一般自行管理类 1', 'sort_order': 2, 'is_system': True},
        {'group_code': 'importance_level', 'option_code': '4', 'option_label': '一般 4', 'sort_order': 3, 'is_system': True},
        {'group_code': 'importance_level', 'option_code': '3', 'option_label': '核心 3', 'sort_order': 4, 'is_system': True},
        {'group_code': 'importance_level', 'option_code': '2', 'option_label': '重要 2', 'sort_order': 5, 'is_system': True},
    ]
    
    for option_data in options_data:
        group_code = option_data.pop('group_code')
        DropdownOption.objects.create(
            group=groups[group_code],
            **option_data
        )


def reverse_init_dropdown_data(apps, schema_editor):
    """回滚初始化数据"""
    DropdownGroup = apps.get_model('work_tools', 'DropdownGroup')
    DropdownOption = apps.get_model('work_tools', 'DropdownOption')
    
    # 删除所有配置项（级联删除）
    DropdownGroup.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0004_dropdowngroup_dropdownoption"),
    ]

    operations = [
        migrations.RunPython(init_dropdown_data, reverse_init_dropdown_data),
    ]
