# Generated by Django 4.2.27 on 2025-12-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0005_init_dropdown_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOrgDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="登录名"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="用户名"
                    ),
                ),
                (
                    "dept_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="部门编码"
                    ),
                ),
                (
                    "dept_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="部门名称"
                    ),
                ),
                (
                    "company_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司编码"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="公司名称"
                    ),
                ),
                (
                    "plate_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="板块编码"
                    ),
                ),
                (
                    "plate_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="板块名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户组织机构",
                "verbose_name_plural": "用户组织机构",
                "db_table": "user_org_detail",
            },
        ),
    ]
