# Generated by Django 4.2.27 on 2025-12-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0006_userorgdetail"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigurableTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_code",
                    models.CharField(max_length=50, unique=True, verbose_name="表编码"),
                ),
                (
                    "table_name",
                    models.CharField(max_length=100, verbose_name="数据库表名"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="显示名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="功能描述")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "可配置表",
                "verbose_name_plural": "可配置表",
                "db_table": "configurable_table",
                "ordering": ["sort_order", "table_code"],
            },
        ),
        migrations.CreateModel(
            name="ConfigurableField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_type",
                    models.CharField(
                        choices=[("update", "修改字段"), ("query", "查询字段")],
                        max_length=20,
                        verbose_name="字段类型",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=100, verbose_name="数据库字段名"),
                ),
                (
                    "display_name",
                    models.CharField(max_length=200, verbose_name="显示名称"),
                ),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "文本"),
                            ("number", "数字"),
                            ("date", "日期"),
                        ],
                        max_length=20,
                        verbose_name="数据类型",
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(default=False, verbose_name="是否必填"),
                ),
                (
                    "max_length",
                    models.IntegerField(blank=True, null=True, verbose_name="最大长度"),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, verbose_name="默认值"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="work_tools.configurabletable",
                        verbose_name="所属表",
                    ),
                ),
            ],
            options={
                "verbose_name": "可配置字段",
                "verbose_name_plural": "可配置字段",
                "db_table": "configurable_field",
                "ordering": ["table", "field_type", "sort_order", "field_name"],
                "indexes": [
                    models.Index(
                        fields=["table", "field_type", "is_active"],
                        name="configurabl_table_i_8911c6_idx",
                    ),
                    models.Index(
                        fields=["table", "field_name"],
                        name="configurabl_table_i_861590_idx",
                    ),
                ],
                "unique_together": {("table", "field_name")},
            },
        ),
    ]
