# Generated by Django 4.2.27 on 2025-12-10 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0007_add_configurable_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurabletable",
            name="sql_file_prefix",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="SQL文件名前缀"
            ),
        ),
    ]
