# Generated by Django 4.2.27 on 2025-12-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0008_configurabletable_sql_file_prefix"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "config_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="配置编码"
                    ),
                ),
                (
                    "config_name",
                    models.CharField(max_length=100, verbose_name="配置名称"),
                ),
                (
                    "db_host",
                    models.CharField(max_length=255, verbose_name="数据库地址"),
                ),
                ("db_name", models.CharField(max_length=100, verbose_name="数据库名")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "数据库配置",
                "verbose_name_plural": "数据库配置",
                "db_table": "database_config",
                "ordering": ["sort_order", "config_code"],
            },
        ),
        migrations.RemoveField(
            model_name="configurabletable",
            name="sql_file_prefix",
        ),
        migrations.AddField(
            model_name="configurablefield",
            name="is_nullable",
            field=models.BooleanField(default=True, verbose_name="是否可为空"),
        ),
        migrations.AddField(
            model_name="configurablefield",
            name="sql_file_name",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="SQL文件名"
            ),
        ),
    ]
