# Generated by Django 4.2.27 on 2025-12-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0009_databaseconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurabletable",
            name="database_configs",
            field=models.ManyToManyField(
                blank=True,
                related_name="tables",
                to="work_tools.databaseconfig",
                verbose_name="启用的数据库配置",
            ),
        ),
    ]
