# Generated by Django 4.2.27 on 2025-12-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("work_tools", "0010_configurabletable_database_configs"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurablefield",
            name="dropdown_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fields",
                to="work_tools.dropdowngroup",
                verbose_name="下拉框数据源分组",
            ),
        ),
        migrations.AlterField(
            model_name="configurablefield",
            name="data_type",
            field=models.CharField(
                choices=[
                    ("text", "文本"),
                    ("number", "数字"),
                    ("date", "日期"),
                    ("dropdown", "下拉框"),
                ],
                max_length=20,
                verbose_name="数据类型",
            ),
        ),
    ]
