# Generated by Django 4.2.27 on 2026-02-10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("work_tools", "0001_initial"),
    ]

    operations = [
        # 添加新的值模式字段
        migrations.AddField(
            model_name="configurablefield",
            name="query_value_mode",
            field=models.CharField(
                choices=[
                    ("required", "必填"),
                    ("nullable_essential", "不必填-必要"),
                    ("nullable_optional", "不必填-不必要"),
                ],
                default="required",
                help_text="必填:值不能为空; 不必填-必要:值为空也生成; 不必填-不必要:值为空不生成",
                max_length=20,
                verbose_name="查询值模式",
            ),
        ),
        migrations.AddField(
            model_name="configurablefield",
            name="new_value_mode",
            field=models.CharField(
                choices=[
                    ("required", "必填"),
                    ("nullable_essential", "不必填-必要"),
                    ("nullable_optional", "不必填-不必要"),
                ],
                default="required",
                help_text="必填:值不能为空; 不必填-必要:值为空也生成(a=''); 不必填-不必要:值为空不生成",
                max_length=20,
                verbose_name="新值模式",
            ),
        ),
        migrations.AddField(
            model_name="configurablefield",
            name="orig_value_mode",
            field=models.CharField(
                choices=[
                    ("required", "必填"),
                    ("nullable_essential", "不必填-必要"),
                    ("nullable_optional", "不必填-不必要"),
                ],
                default="required",
                help_text="必填:值不能为空; 不必填-必要:值为空也生成(a=''); 不必填-不必要:值为空不生成",
                max_length=20,
                verbose_name="原值模式",
            ),
        ),
        # 删除旧的必填字段
        migrations.RemoveField(
            model_name="configurablefield",
            name="query_required",
        ),
        migrations.RemoveField(
            model_name="configurablefield",
            name="new_required",
        ),
        migrations.RemoveField(
            model_name="configurablefield",
            name="orig_required",
        ),
    ]
