"""
Django settings for work_tools project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging.handlers
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-hojut)v+nufl=fjd!bt+#bn8g@0i504big-v#9=!(em!7jmq@%"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']  # 允许所有主机（仅开发环境）


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "work_tools.apps.WorkToolsConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "work_tools.middleware.RequestLoggingMiddleware",  # 请求日志中间件
]

ROOT_URLCONF = "work_tools.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "work_tools.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
        "OPTIONS": {"timeout": 30},
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 简化的日志配置 - 直接写入文件,避免复杂配置导致的问题
import sys

# 获取运行时基础目录（支持打包后的exe和源码运行）
def get_runtime_base():
    if getattr(sys, 'frozen', False):
        return os.path.dirname(sys.executable)
    return BASE_DIR

RUNTIME_BASE_DIR = get_runtime_base()

# 创建日志目录
LOG_DIR = os.path.join(RUNTIME_BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)

# 完全禁用Django默认日志配置,使用自定义简单配置
LOGGING_CONFIG = None

# 手动配置日志


def setup_logging():
    """手动设置日志系统,确保日志能够正常写入"""
    # 创建格式化器
    formatter = logging.Formatter(
        '[%(asctime)s] %(levelname)s [%(name)s:%(funcName)s:%(lineno)d] %(message)s',
        datefmt='%Y-%m-%d %H:%M:%S'
    )

    # 请求日志
    request_handler = logging.handlers.RotatingFileHandler(
        os.path.join(LOG_DIR, 'requests.log'),
        maxBytes=10*1024*1024,
        backupCount=10,
        encoding='utf-8'
    )
    request_handler.setFormatter(formatter)
    request_handler.setLevel(logging.INFO)

    request_logger = logging.getLogger('app.request')
    request_logger.setLevel(logging.INFO)
    request_logger.addHandler(request_handler)
    request_logger.addHandler(logging.StreamHandler())

    # SQL生成日志
    sql_handler = logging.handlers.RotatingFileHandler(
        os.path.join(LOG_DIR, 'sql.log'),
        maxBytes=10*1024*1024,
        backupCount=10,
        encoding='utf-8'
    )
    sql_handler.setFormatter(formatter)
    sql_handler.setLevel(logging.INFO)

    sql_logger = logging.getLogger('app.sql')
    sql_logger.setLevel(logging.INFO)
    sql_logger.addHandler(sql_handler)
    sql_logger.addHandler(logging.StreamHandler())

    # 视图日志
    view_handler = logging.handlers.RotatingFileHandler(
        os.path.join(LOG_DIR, 'views.log'),
        maxBytes=10*1024*1024,
        backupCount=10,
        encoding='utf-8'
    )
    view_handler.setFormatter(formatter)
    view_handler.setLevel(logging.INFO)

    view_logger = logging.getLogger('app.view')
    view_logger.setLevel(logging.INFO)
    view_logger.addHandler(view_handler)
    view_logger.addHandler(logging.StreamHandler())

    # 错误日志
    error_handler = logging.handlers.RotatingFileHandler(
        os.path.join(LOG_DIR, 'errors.log'),
        maxBytes=10*1024*1024,
        backupCount=10,
        encoding='utf-8'
    )
    error_handler.setFormatter(formatter)
    error_handler.setLevel(logging.ERROR)

    error_logger = logging.getLogger('app.error')
    error_logger.setLevel(logging.ERROR)
    error_logger.addHandler(error_handler)
    error_logger.addHandler(logging.StreamHandler())

    # 写入启动日志验证
    request_logger.info('='*80)
    request_logger.info('日志系统初始化成功 - 请求日志')
    request_logger.info(f'日志目录: {LOG_DIR}')
    request_logger.info('='*80)

    sql_logger.info('='*80)
    sql_logger.info('日志系统初始化成功 - SQL日志')
    sql_logger.info('='*80)

    view_logger.info('='*80)
    view_logger.info('日志系统初始化成功 - 视图日志')
    view_logger.info('='*80)


# 立即初始化日志
setup_logging()
